//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementSystemMVCApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inpatient
    {
        public int patient_id { get; set; }
        public System.DateTime admission_date { get; set; }
        public Nullable<int> doctor_assigned { get; set; }
        public string disease { get; set; }
        public Nullable<int> room_assigned { get; set; }
    }
}
